### ISSUE TITLE
Model copy issue on windows

### ISSUE THREAD

**Issue by mehdidc** [scikit-learn-contrib/py-earth#106]
After setting up appveyor, it seems we have the following issues on Windows:

```
======================================================================
FAIL: pyearth.test.test_earth.test_pickle_compatibility
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\projects\py-earth\pyearth\test\test_earth.py", line 287, in test_pickle_compatibility
    numpy.all(model.predict(X) == model_copy.predict(X)))
AssertionError: False is not true
 
======================================================================
FAIL: pyearth.test.test_earth.test_copy_compatibility
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\projects\py-earth\pyearth\test\test_earth.py", line 297, in test_copy_compatibility
    numpy.all(model.predict(X) == model_copy.predict(X)))
AssertionError: False is not true
```

**Comment by mehdidc** [comment]
Weird the error doesn't seem to occur now : https://ci.appveyor.com/project/mehdidc/py-earth/build/job/iv62wobvpxxswt8d
