### ISSUE TITLE
issue installing py-earth Windows 10 python 2.7 

### ISSUE THREAD

**Issue by nikrepp** [scikit-learn-contrib/py-earth#170]
Hello,

thank you for the nice package.

I am facing the issue running install script:

C:\Users\I304909\AppData\Local\Continuum\Miniconda2\py-earth-master\py-earth-master>python setup.py install
install_dir .
c:\users\i304909\appdata\local\temp\easy_install-7zu8zz\numpy-1.13.3\setup.py:367: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
  run_build = parse_setuppy_commands()
C:\Users\I304909\AppData\Local\Continuum\Miniconda2\lib\distutils\dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
Traceback (most recent call last):
  File "setup.py", line 163, in <module>
    setup_package()
  File "setup.py", line 160, in setup_package
    setup(**setup_args)
  File "C:\Users\I304909\AppData\Local\Continuum\Miniconda2\lib\distutils\core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "C:\Users\I304909\AppData\Local\Continuum\Miniconda2\lib\site-packages\distribute-0.6.14-py2.7.egg\setuptools\dist.py", line 221, in __init__
    self.fetch_build_eggs(attrs.pop('setup_requires'))
  File "C:\Users\I304909\AppData\Local\Continuum\Miniconda2\lib\site-packages\distribute-0.6.14-py2.7.egg\setuptools\dist.py", line 245, in fetch_build_eggs
    parse_requirements(requires), installer=self.fetch_build_egg
  File "C:\Users\I304909\AppData\Local\Continuum\Miniconda2\lib\site-packages\distribute-0.6.14-py2.7.egg\pkg_resources.py", line 544, in resolve
    dist = best[req.key] = env.best_match(req, self, installer)
  File "C:\Users\I304909\AppData\Local\Continuum\Miniconda2\lib\site-packages\distribute-0.6.14-py2.7.egg\pkg_resources.py", line 786, in best_match
    return self.obtain(req, installer) # try and download/install
  File "C:\Users\I304909\AppData\Local\Continuum\Miniconda2\lib\site-packages\distribute-0.6.14-py2.7.egg\pkg_resources.py", line 798, in obtain
    return installer(requirement)
  File "C:\Users\I304909\AppData\Local\Continuum\Miniconda2\lib\site-packages\distribute-0.6.14-py2.7.egg\setuptools\dist.py", line 293, in fetch_build_egg
    return cmd.easy_install(req)
  File "C:\Users\I304909\AppData\Local\Continuum\Miniconda2\lib\site-packages\distribute-0.6.14-py2.7.egg\setuptools\command\easy_install.py", line 582, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "C:\Users\I304909\AppData\Local\Continuum\Miniconda2\lib\site-packages\distribute-0.6.14-py2.7.egg\setuptools\command\easy_install.py", line 612, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "C:\Users\I304909\AppData\Local\Continuum\Miniconda2\lib\site-packages\distribute-0.6.14-py2.7.egg\setuptools\command\easy_install.py", line 802, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "C:\Users\I304909\AppData\Local\Continuum\Miniconda2\lib\site-packages\distribute-0.6.14-py2.7.egg\setuptools\command\easy_install.py", line 1079, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "C:\Users\I304909\AppData\Local\Continuum\Miniconda2\lib\site-packages\distribute-0.6.14-py2.7.egg\setuptools\command\easy_install.py", line 1068, in run_setup
    run_setup(setup_script, args)
  File "C:\Users\I304909\AppData\Local\Continuum\Miniconda2\lib\site-packages\distribute-0.6.14-py2.7.egg\setuptools\sandbox.py", line 29, in run_setup
    lambda: execfile(
  File "C:\Users\I304909\AppData\Local\Continuum\Miniconda2\lib\site-packages\distribute-0.6.14-py2.7.egg\setuptools\sandbox.py", line 70, in run
    return func()
  File "C:\Users\I304909\AppData\Local\Continuum\Miniconda2\lib\site-packages\distribute-0.6.14-py2.7.egg\setuptools\sandbox.py", line 31, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "setup.py", line 392, in <module>

  File "setup.py", line 384, in setup_package

  File "C:\Users\I304909\AppData\Local\Continuum\Miniconda2\lib\site-packages\numpy\distutils\core.py", line 135, in setup
    config = configuration()
  File "setup.py", line 166, in configuration

  File "C:\Users\I304909\AppData\Local\Continuum\Miniconda2\lib\site-packages\numpy\distutils\misc_util.py", line 1029, in add_subpackage
    caller_level = 2)
  File "C:\Users\I304909\AppData\Local\Continuum\Miniconda2\lib\site-packages\numpy\distutils\misc_util.py", line 998, in get_subpackage
    caller_level = caller_level + 1)
  File "C:\Users\I304909\AppData\Local\Continuum\Miniconda2\lib\site-packages\numpy\distutils\misc_util.py", line 935, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "numpy\setup.py", line 10, in configuration
    else:
  File "C:\Users\I304909\AppData\Local\Continuum\Miniconda2\lib\site-packages\numpy\distutils\misc_util.py", line 1029, in add_subpackage
    caller_level = 2)
  File "C:\Users\I304909\AppData\Local\Continuum\Miniconda2\lib\site-packages\numpy\distutils\misc_util.py", line 998, in get_subpackage
    caller_level = caller_level + 1)
  File "C:\Users\I304909\AppData\Local\Continuum\Miniconda2\lib\site-packages\numpy\distutils\misc_util.py", line 911, in _get_configuration_from_setup_py
    ('.py', 'U', 1))
  File "C:\Users\I304909\AppData\Local\Continuum\Miniconda2\lib\site-packages\numpy\compat\py3k.py", line 153, in npy_load_module
    mod = imp.load_module(name, fo, fn, info)
  File "numpy\core\setup.py", line 13, in <module>
    def get_ext_modules():
ImportError: No module named _build_utils.apple_accelerate

Regards,
Nikita

**Comment by nikrepp** [comment]
I fixed that
